### ISSUE TITLE
Benefits over aws-lambda-java-runtime-interface-client?

### ISSUE THREAD

**Issue by kito99** [formkiq/lambda-runtime-graalvm#12]
I'm guessing this project preceded the open sourcing of https://github.com/aws/aws-lambda-java-libs, but now that it's available, what is the benefit of using this library instead?

**Comment by mfriesen** [comment]
This project is a AWS lambda runtime for projects using https://www.graalvm.org. 
 
 https://github.com/aws/aws-lambda-java-libs is used to for creating AWS Lambda functions.
This project is would call the lambda created using  https://github.com/aws/aws-lambda-java-libs.

**Comment by kito99** [comment]
@mfriesen my bad, I meant to link to the Runtime Interface Client: https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-runtime-interface-client/README.md. This is a lambda runtime that works with GraalVM (or with other JVMs).
