### ISSUE TITLE
Use Jackson instead of Gson

### ISSUE THREAD

**Issue by NikolayMetchev** [formkiq/lambda-runtime-graalvm#17]
We are using aws lambda java events (https://github.com/aws/aws-lambda-java-libs/tree/main/aws-lambda-java-events). 
It seems Gson doesn't serialize these events correctly. It seems to get the case of some of the elements wrong.
If you use Jackson which I think is what the AWS runtime uses as well there shouldn't be any compatibility issues.

**Comment by mfriesen** [comment]
Version 2.5.0 has just been released which supports lambda java events. The reason for Gson instead of Jackson is due to the library size of Jackson is much larger and we want to keep this library small so the lambda performance is better.
