### ISSUE TITLE
Propagate X-Ray tracing header

### ISSUE THREAD

**Issue by Morras** [formkiq/lambda-runtime-graalvm#5]
According to the custom runtime documentation, the processing task should 

> **Propagate the tracing header** – Get the X-Ray tracing header from the `Lambda-Runtime-Trace-Id `header in the API response. Set the `_X_AMZN_TRACE_ID` environment variable locally with the same value. The X-Ray SDK uses this value to connect trace data between services.

Without the `_X_AMZN_TRACE_ID` the X-Ray SDK cannot create subsegments which essentially means X-Ray cannot be used with Lambda functions running with this graalvm runtime.

**Comment by mfriesen** [comment]
@Morras should be fixed in 2.2.0 release. Please let me know if that fixes your issue.

**Comment by Morras** [comment]
Thank you so much for looking at this @mfriesen .

Unfortunately it does not work. 

The X-Ray SDK is reading the value from the environment variables and not the system properties.
For reference the relevant SDK code is line 40 of [this class](https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/contexts/LambdaSegmentContext.java) and line 49-52 is the error I am getting when I run the Lambda function on graalvm.

Unfortunately there does not appear to be an easy way of changing environment variables at runtime from Java. 
Work arounds are discussed in [this StackOverflow post](https://stackoverflow.com/questions/318239/how-do-i-set-environment-variables-from-java). Considering this would only need to work on Lambda's Linux environment, a workaround might be possible, but not that pretty.

**Comment by mfriesen** [comment]
Hopefully this PR will get merged and the issue should be solved. https://github.com/aws/aws-xray-sdk-java/issues/251

**Comment by mfriesen** [comment]
Waiting on https://github.com/aws/aws-xray-sdk-java/issues/251 to be released. This should be fixed for aws-xray-sdk-java > 2.8.0

**Comment by Morras** [comment]
We are running a fork of the next version of aws-xray-sdk-java to get this functionality, and I can confirm that this works with that version.
